modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Keep%20My%20Soil%20Tilled"
logoFile="icon.png"

[[mods]]
modId="keepmysoiltilled"
version="2.2"
displayName="Keep My Soil Tilled"
displayURL="https://serilum.com/mod/keep-my-soil-tilled"
authors="Rick South"
description='''Keeps soil tilled below a stem block (melon/pumpkin) after harvesting.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.keepmysoiltilled]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.keepmysoiltilled]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "keepmysoiltilled_neoforge.mixins.json"